# television configuration
# See: https://github.com/alexpasmantier/television

[ui]
use_nerd_font_icons = true

[shell_integration.channel_triggers]
dirs = ["cd", "ls"]
env = ["set"]
files = ["bat", "cat", "cp", "less", "more", "mv"]

# Custom channels can be defined here
# [channels.git-log]
# name = "Git Log"
# source_command = "git log --oneline --date=short --pretty=\"format:%h %s %an %cd\" \"$@\""
# preview_command = "git show -p --stat --pretty=fuller --color=always {0}"
